### ISSUE TITLE
simple_server_application_with_auto_handler C++x11 don't compile

### ISSUE THREAD

**Issue by retf** [retf/Boost.Application#25]
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler.test
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler.test/gcc-4.6
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler.test/gcc-4.6/debug
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler.test/gcc-4.6/debug/threading-multi
gcc.compile.c++ ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler.test/gcc-4.6/debug/threading-multi/simple_server_application_with_auto_handler.o
In file included from ../../../boost/application/all.hpp:26:0,
                 from ../../../boost/application.hpp:14,
                 from ../example/simple_server_application_with_auto_handler.cpp:62:
../../../boost/application/auto_handler.hpp: In constructor ‘boost::application::detail::handler_auto_set_u<Application, Derived>::handler_auto_set_u(boost::application::context&) [with Application = myapp, Derived = boost::application::auto_handler<myapp>, boost::application::context = boost::application::basic_context]’:
../../../boost/application/auto_handler.hpp:194:29:   instantiated from ‘boost::application::auto_handler<Application>::auto_handler(boost::application::context&) [with Application = myapp, boost::application::context = boost::application::basic_context]’
../example/simple_server_application_with_auto_handler.cpp:249:52:   instantiated from here
../../../boost/application/auto_handler.hpp:119:10: error: no matching function for call to ‘myapp::myapp()’
../../../boost/application/auto_handler.hpp:119:10: note: candidate is:
../example/simple_server_application_with_auto_handler.cpp:79:4: note: myapp::myapp(boost::application::context&)
../example/simple_server_application_with_auto_handler.cpp:79:4: note:   candidate expects 1 argument, 0 provided
../../../boost/asio/error.hpp: At global scope:
../../../boost/asio/error.hpp:253:45: warning: ‘boost::asio::error::system_category’ defined but not used [-Wunused-variable]
../../../boost/asio/error.hpp:255:45: warning: ‘boost::asio::error::netdb_category’ defined but not used [-Wunused-variable]
../../../boost/asio/error.hpp:257:45: warning: ‘boost::asio::error::addrinfo_category’ defined but not used [-Wunused-variable]
../../../boost/asio/error.hpp:259:45: warning: ‘boost::asio::error::misc_category’ defined but not used [-Wunused-variable]
    "g++"  -ftemplate-depth-128 -O0 -fno-inline -Wall -g -pthread -fPIC --coverage -std=c++0x -fno-strict-aliasing -DBOOST_ALL_DLL -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_DYN_LINK=1 -DBOOST_DATE_TIME_DYN_LINK=1 -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_PROGRAM_OPTIONS_DYN_LINK=1 -DBOOST_SYSTEM_DYN_LINK=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_TEST_NO_AUTO_LINK=1 -DBOOST_THREAD_BUILD_DLL=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_DLL=1 -DDATE_TIME_INLINE  -I"../../.." -I"../../../../type_index" -c -o "../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler.test/gcc-4.6/debug/threading-multi/simple_server_application_with_auto_handler.o" "../example/simple_server_application_with_auto_handler.cpp"
...failed gcc.compile.c++ ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler.test/gcc-4.6/debug/threading-multi/simple_server_application_with_auto_handler.o...
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler_and_global_context.test
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler_and_global_context.test/gcc-4.6
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler_and_global_context.test/gcc-4.6/debug
common.mkdir ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler_and_global_context.test/gcc-4.6/debug/threading-multi
gcc.compile.c++ ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler_and_global_context.test/gcc-4.6/debug/threading-multi/simple_server_application_with_auto_handler_and_global_context.o
**passed** ../../../bin.v2/libs/application/test/simple_server_application_with_auto_handler_and_global_context.test/gcc-4.6/debug/threading-multi/simple_server_application_with_auto_handler_and_global_context.test
...failed updating 1 target...
...skipped 1 target...
...updated 233 targets...
The command "../../../b2 cxxflags="--coverage -std=$CXX_STANDARD" linkflags="--coverage"" exited with 1.
Done. Your build exited with 1.

**Comment by oliora** [comment]
Most probably this bug is fixed by 18e28c9c40c6a9b10621c74c8ec857a22ce984d1
It's seems to be related to change `boost::is_convertible<context, Application>::value` => `boost::is_convertible<context&, Application>::value`

**Comment by retf** [comment]
Ok, I will check. Thanks
